# -*- coding: utf-8 -*-
"""Food_Wastage_Management_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0XIE_dfx9Z2_98tjNzLdZuH3HVFQZAX
"""

from google.colab import files
uploaded = files.upload()

import sqlite3
import pandas as pd

conn = sqlite3.connect("food_wastage.db")

providers = pd.read_csv("providers_data.csv")
receivers = pd.read_csv("receivers_data.csv")
food = pd.read_csv("food_listings_data.csv")
claims = pd.read_csv("claims_data.csv")

providers.to_sql("providers", conn, if_exists="replace", index=False)
receivers.to_sql("receivers", conn, if_exists="replace", index=False)
food.to_sql("food_listings", conn, if_exists="replace", index=False)
claims.to_sql("claims", conn, if_exists="replace", index=False)

print("Database ready!")

# Query 1 - How many providers and receivers in each city?
q1 = """
SELECT p.City,
       COUNT(DISTINCT p.Provider_ID) as Total_Providers,
       COUNT(DISTINCT r.Receiver_ID) as Total_Receivers
FROM providers p
LEFT JOIN receivers r ON p.City = r.City
GROUP BY p.City
ORDER BY Total_Providers DESC
"""
df1 = pd.read_sql_query(q1, conn)
print("Providers & Receivers per City:-")
print(df1)

# Query 2 - Which provider type contributes most food?
q2 = """
SELECT Provider_Type, COUNT(*) as Total_Listings,
       SUM(Quantity) as Total_Quantity
FROM food_listings
GROUP BY Provider_Type
ORDER BY Total_Quantity DESC
"""
df2 = pd.read_sql_query(q2, conn)
print("Provider Type Contributions:-")
print(df2)

# Query 3 - Contact info of providers in a specific city
q3 = """
SELECT Name, Type, Address, City, Contact
FROM providers
WHERE City = 'Mumbai'
"""
df3 = pd.read_sql_query(q3, conn)
print("Provider Contact Info by City:-")
print(df3)

# Query 4 - Which receivers claimed the most food?
q4 = """
SELECT r.Name, r.Type, r.City,
       COUNT(c.Claim_ID) as Total_Claims
FROM receivers r
JOIN claims c ON r.Receiver_ID = c.Receiver_ID
GROUP BY r.Receiver_ID
ORDER BY Total_Claims DESC
LIMIT 10
"""
df4 = pd.read_sql_query(q4, conn)
print("Top Receivers by Claims:-")
print(df4)

# Query 5 - Total quantity of food available
q5 = """
SELECT SUM(Quantity) as Total_Food_Available
FROM food_listings
"""
df5 = pd.read_sql_query(q5, conn)
print("Total Food Available:-")
print(df5)

# Query 6 - Which city has highest food listings?
q6 = """
SELECT Location as City,
       COUNT(*) as Total_Listings,
       SUM(Quantity) as Total_Quantity
FROM food_listings
GROUP BY Location
ORDER BY Total_Listings DESC
LIMIT 10
"""
df6 = pd.read_sql_query(q6, conn)
print("City wise Food Listings:-")
print(df6)

# Query 7 - Most commonly available food types?
q7 = """
SELECT Food_Type,
       COUNT(*) as Total_Listings,
       SUM(Quantity) as Total_Quantity
FROM food_listings
GROUP BY Food_Type
ORDER BY Total_Listings DESC
"""
df7 = pd.read_sql_query(q7, conn)
print("Most Common Food Types:-")
print(df7)

# Query 8 - How many claims made for each food item?
q8 = """
SELECT f.Food_Name,
       COUNT(c.Claim_ID) as Total_Claims
FROM food_listings f
LEFT JOIN claims c ON f.Food_ID = c.Food_ID
GROUP BY f.Food_Name
ORDER BY Total_Claims DESC
"""
df8 = pd.read_sql_query(q8, conn)
print("Claims per Food Item:-")
print(df8)

# Query 9 - Which provider had highest successful claims?
q9 = """
SELECT p.Name, p.Type, p.City,
       COUNT(c.Claim_ID) as Successful_Claims
FROM providers p
JOIN food_listings f ON p.Provider_ID = f.Provider_ID
JOIN claims c ON f.Food_ID = c.Food_ID
WHERE c.Status = 'Completed'
GROUP BY p.Provider_ID
ORDER BY Successful_Claims DESC
LIMIT 10
"""
df9 = pd.read_sql_query(q9, conn)
print("Top Providers by Successful Claims:-")
print(df9)

# Query 10 - Percentage of completed vs pending vs cancelled?
q10 = """
SELECT Status,
       COUNT(*) as Total,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM claims), 2) as Percentage
FROM claims
GROUP BY Status
"""
df10 = pd.read_sql_query(q10, conn)
print("Claim Status Percentage:-")
print(df10)

# Query 11 - Average quantity claimed per receiver?
q11 = """
SELECT r.Name,
       AVG(f.Quantity) as Avg_Quantity_Claimed
FROM receivers r
JOIN claims c ON r.Receiver_ID = c.Receiver_ID
JOIN food_listings f ON c.Food_ID = f.Food_ID
GROUP BY r.Receiver_ID
ORDER BY Avg_Quantity_Claimed DESC
LIMIT 10
"""
df11 = pd.read_sql_query(q11, conn)
print("Average Quantity per Receiver:-")
print(df11)

# Query 12 - Which meal type is claimed the most?
q12 = """
SELECT f.Meal_Type,
       COUNT(c.Claim_ID) as Total_Claims
FROM food_listings f
JOIN claims c ON f.Food_ID = c.Food_ID
GROUP BY f.Meal_Type
ORDER BY Total_Claims DESC
"""
df12 = pd.read_sql_query(q12, conn)
print("Most Claimed Meal Type:-")
print(df12)

# Query 13 - Total quantity donated by each provider?
q13 = """
SELECT p.Name, p.Type, p.City,
       SUM(f.Quantity) as Total_Donated
FROM providers p
JOIN food_listings f ON p.Provider_ID = f.Provider_ID
GROUP BY p.Provider_ID
ORDER BY Total_Donated DESC
LIMIT 10
"""
df13 = pd.read_sql_query(q13, conn)
print("Total Donation per Provider:-")
print(df13)